ref: add tomcat status check after startup and sudo for folder removal

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -21,10 +21,12 @@ jobs:
             
             # Step 1: Stop Tomcat to prevent the server from hanging (optional if already stopped)
             echo "Stopping Tomcat..."
+            
             /opt/tomcat/apache-tomcat-10.1.26/bin/shutdown.sh || true
             
             # Step 2: Backup the current WAR file if it exists
             echo "Backing up the current WAR file..."
+            
             if [ -f /opt/tomcat/apache-tomcat-10.1.26/webapps/tennis-scoreboard.war ]; then
               mv /opt/tomcat/apache-tomcat-10.1.26/webapps/tennis-scoreboard.war /opt/tomcat/apache-tomcat-10.1.26/webapps/tennis-scoreboard.war.bak
             else
@@ -33,8 +35,9 @@ jobs:
             
             # Step 3: Remove the old extracted folder if it exists
             echo "Removing old extracted folder..."
+            
             if [ -d /opt/tomcat/apache-tomcat-10.1.26/webapps/tennis-scoreboard ]; then
-              rm -rf /opt/tomcat/apache-tomcat-10.1.26/webapps/tennis-scoreboard
+              sudo rm -rf /opt/tomcat/apache-tomcat-10.1.26/webapps/tennis-scoreboard
               echo "Old folder removed."
             else
               echo "No existing folder found to remove."
@@ -42,10 +45,21 @@ jobs:
 
             # Step 4: Download the latest release WAR file using the GitHub API to get the latest release dynamically
             echo "Downloading the latest WAR file..."
+            
             LATEST_RELEASE=$(curl -s https://api.github.com/repos/aleos-dev/tennis-scoreboard/releases/latest | grep "browser_download_url.*war" | cut -d : -f 2,3 | tr -d \" | tr -d ' ')
             echo $LATEST_RELEASE
             wget $LATEST_RELEASE -O /opt/tomcat/apache-tomcat-10.1.26/webapps/tennis-scoreboard.war
             
             # Step 5: Start Tomcat using startup.sh
             echo "Starting Tomcat..."
+            
             /opt/tomcat/apache-tomcat-10.1.26/bin/startup.sh
+            
+            echo "Checking if Tomcat started..."
+            if curl -s http://localhost:9091/ > /dev/null; then
+              echo "Tomcat is running."
+            else
+              echo "Tomcat failed to start."
+              tail -n 50 /opt/tomcat/apache-tomcat-10.1.26/logs/catalina.out
+              exit 1
+            fi
